### ISSUE TITLE
Security Vulnerability Warning

### ISSUE THREAD

**Issue by dipstar** [githubtraining/on-demand-merge-conflict#2]
Hi @githubteacher 

I have cloned this repo and now get the following security alert for one of the dependencies:

"We found a potential security vulnerability in one of your dependencies.

The nokogiri dependency defined in Gemfile.lock has a known critical severity security vulnerability in version range < 1.8.1 and should be updated."

Thanks

**Comment by hectorsector** [comment]
Apologies for the delay, @dipstar! This has now been fixed in 479b0d5. Thank you for catching this.
